// A thin typed client generated by hand from docs/interfaces/api.md (08-
// dashboard.md 2). Every function here is one row of that doc's tables; add
// a function when a route is added there, not before.
import { env } from '$env/dynamic/public';
import { getAccessToken } from '$lib/auth.svelte';
import { ApiError, NetworkError, isOutage } from './errors';
import { reachability } from './reachability.svelte';
import type {
	ApiErrorBody,
	Billing,
	CatalogItem,
	Checkout,
	Config,
	DestroyedProject,
	Invoice,
	Me,
	MenuSelection,
	OpStatus,
	PersonalConfig,
	PutPersonalResult,
	PlanId,
	Project,
	ProjectEvent,
	PublicSeats,
	Question,
	RestoreResult,
	Revision,
	Route,
	SecretMeta,
	Samples,
	SampleWindow,
	Snapshot,
	UsageRow
} from './types';

function baseUrl(): string {
	// Already carries /v1, per api.md's "Base: .../v1".
	return (env.PUBLIC_API_URL ?? '').replace(/\/$/, '');
}

interface RequestOptions {
	method?: string;
	body?: unknown;
	/** Internal: set on the one retry rate_limited gets (5.5). */
	_retried?: boolean;
}

async function request<T>(path: string, opts: RequestOptions = {}): Promise<T> {
	const headers: Record<string, string> = {};
	if (opts.body !== undefined) headers['Content-Type'] = 'application/json';
	const token = await getAccessToken();
	headers['Authorization'] = `Bearer ${token}`;

	let res: Response;
	try {
		res = await fetch(`${baseUrl()}${path}`, {
			method: opts.method ?? 'GET',
			headers,
			body: opts.body !== undefined ? JSON.stringify(opts.body) : undefined
		});
	} catch (err) {
		reachability.down('network');
		throw new NetworkError(err);
	}

	const requestId = res.headers.get('X-Request-Id');

	if (res.status === 204) {
		reachability.up();
		return undefined as T;
	}

	let json: unknown;
	const text = await res.text();
	try {
		json = text ? JSON.parse(text) : undefined;
	} catch {
		// A proxy's HTML error page: the api itself did not answer.
		if (res.status >= 500) reachability.down('server');
		else reachability.up();
		throw new ApiError(
			{ code: 'internal', message: 'the api sent a response that was not JSON' },
			res.status,
			requestId
		);
	}

	const errBody = (json as { error?: ApiErrorBody } | undefined)?.error;
	// A 5xx raises the persistent bar (08-dashboard.md 6), except the 503s
	// the api gives as answers (isOutage); anything else clears it.
	if (isOutage(res.status, errBody?.code)) reachability.down('server');
	else reachability.up();

	if (!res.ok) {
		const body = errBody ?? {
			code: 'internal',
			message: `unexpected ${res.status} response`
		};
		if (body.code === 'rate_limited' && !opts._retried) {
			const retryAfter = Number(res.headers.get('Retry-After') ?? '1');
			await new Promise((r) => setTimeout(r, Math.min(retryAfter, 10) * 1000));
			return request<T>(path, { ...opts, _retried: true });
		}
		throw new ApiError(body, res.status, requestId);
	}

	return json as T;
}

// Users.
export const getMe = () => request<Me>('/me');
export const patchMe = (body: {
	tz?: string;
	notify?: { email?: boolean; ntfy_url?: string | null };
}) => request<Me>('/me', { method: 'PATCH', body });
export const deleteMe = () => request<void>('/me', { method: 'DELETE' });
export const notifyTest = () =>
	request<{ email: 'ok' | 'error'; ntfy: 'ok' | 'error' }>('/me/notify-test', { method: 'POST' });
/** The account's machine.nix (DECISIONS I-490). */
export const getPersonal = () => request<PersonalConfig>('/me/config');
/** Saves machine.nix; base is the revision the text started from, refused with conflict when the account has another. */
export const putPersonal = (fragment: string, base: string | null) =>
	request<PutPersonalResult>('/me/config', {
		method: 'PUT',
		body: { fragment, base_revision_id: base ?? '', source: 'dashboard' }
	});

// Projects.
export const listProjects = () => request<Project[]>('/projects');
export const getProject = (id: string) => request<Project>(`/projects/${id}`);
export const patchProject = (
	id: string,
	body: {
		class?: string;
		hold_base_updates?: boolean;
		agent_default?: string;
		personal_opt_out?: boolean;
	}
) => request<Project>(`/projects/${id}`, { method: 'PATCH', body });
export const destroyProject = (id: string) =>
	request<{ op_id: string; state: string }>(`/projects/${id}`, { method: 'DELETE' });
/** The newest 100 destroyed projects, or with `before` (a project id) the `limit` before it (I-420). */
export const listDestroyed = (opts: { before?: string; limit?: number } = {}) => {
	const q = new URLSearchParams();
	if (opts.before) q.set('before', opts.before);
	if (opts.limit) q.set('limit', String(opts.limit));
	const qs = q.toString();
	return request<DestroyedProject[]>(`/projects/destroyed${qs ? `?${qs}` : ''}`);
};
/** Restores a destroyed (or live) project's newest snapshot as a new project (I-167). */
export const restoreProject = (body: {
	slug?: string;
	project_id?: string;
	snapshot_id?: string;
	name?: string;
}) => request<RestoreResult>('/projects/restore', { method: 'POST', body });
export const startProject = (id: string) =>
	request<{ op_id: string }>(`/projects/${id}/start`, { method: 'POST' });
export const stopProject = (id: string, snapshot = true) =>
	request<{ op_id: string }>(`/projects/${id}/stop`, { method: 'POST', body: { snapshot } });
export const getOp = (projectId: string, opId: string) =>
	request<OpStatus>(`/projects/${projectId}/ops/${opId}`);
export const resizeProject = (id: string, volumeBytes: number) =>
	request<{ op_id: string }>(`/projects/${id}/resize`, {
		method: 'POST',
		body: { volume_bytes: volumeBytes }
	});
export const getProjectRoute = (id: string) => request<Route>(`/projects/${id}/route`);

// Config.
export const getConfig = (id: string) => request<Config>(`/projects/${id}/config`);
export const putConfig = (id: string, body: { fragment: string } | { menu: MenuSelection }) =>
	request<{ revision_id: string; op_id: string }>(`/projects/${id}/config`, {
		method: 'PUT',
		body
	});
export const listRevisions = (id: string) =>
	request<Revision[]>(`/projects/${id}/config/revisions`);
export const applyRevision = (id: string, rev: string) =>
	request<{ op_id: string }>(`/projects/${id}/config/revisions/${rev}/apply`, { method: 'POST' });
export const getCatalog = () => request<CatalogItem[]>('/catalog');

// Secrets.
export const listSecrets = (id: string) => request<SecretMeta[]>(`/projects/${id}/secrets`);
export const putSecret = (id: string, name: string, valueBase64: string) =>
	request<void>(`/projects/${id}/secrets/${encodeURIComponent(name)}`, {
		method: 'PUT',
		body: { value: valueBase64 }
	});
export const deleteSecret = (id: string, name: string) =>
	request<void>(`/projects/${id}/secrets/${encodeURIComponent(name)}`, { method: 'DELETE' });

// Snapshots.
export const getSamples = (id: string, window: SampleWindow) =>
	request<Samples>(`/projects/${id}/samples?window=${window}`);
export const listSnapshots = (id: string) => request<Snapshot[]>(`/projects/${id}/snapshots`);
export const createSnapshot = (id: string) =>
	request<{ op_id: string }>(`/projects/${id}/snapshots`, { method: 'POST' });
export const restoreSnapshot = (id: string, snapshotId: string, asNewProject?: string) =>
	request<{ op_id: string }>(`/projects/${id}/snapshots/${snapshotId}/restore`, {
		method: 'POST',
		body: asNewProject ? { as_new_project: asNewProject } : {}
	});

// Events and logs.
/** The newest 50 events, or with `before` (an event id) the `limit` before it (I-414). */
export const listEvents = (
	id: string,
	opts: { since?: string; before?: string; limit?: number } = {}
) => {
	const q = new URLSearchParams();
	if (opts.since) q.set('since', opts.since);
	if (opts.before) q.set('before', opts.before);
	if (opts.limit) q.set('limit', String(opts.limit));
	const qs = q.toString();
	return request<ProjectEvent[]>(`/projects/${id}/events${qs ? `?${qs}` : ''}`);
};

// Questions (repose-ask, I-245).
export const listProjectQuestions = (id: string, pendingOnly = true) =>
	request<{ questions: Question[] }>(
		`/projects/${id}/questions${pendingOnly ? '?state=pending' : ''}`
	).then((r) => r.questions);
export const answerQuestion = (id: string, qid: string, answer: string) =>
	request<Question>(`/projects/${id}/questions/${qid}/answer`, {
		method: 'POST',
		body: { answer, via: 'dashboard' }
	});
export const cancelQuestion = (id: string, qid: string) =>
	request<Question>(`/projects/${id}/questions/${qid}/cancel`, { method: 'POST' });

// Usage and billing.
export const getUsage = (from: string, to: string) =>
	request<Array<{ project_id: string; day: string } & UsageRow>>(
		`/usage?from=${encodeURIComponent(from)}&to=${encodeURIComponent(to)}`
	);
export const getBilling = () => request<Billing>('/billing');
/** Opens a Polar checkout for the plan (I-604) and answers its URL; `waitlisted` when its seats are not free. */
export const billingCheckout = (plan: PlanId) =>
	request<Checkout>('/billing/checkout', { method: 'POST', body: { plan } });
export const billingJoinWaitlist = () =>
	request<{ position: number; joined_at: string }>('/billing/waitlist', { method: 'POST' });
export const billingChangePlan = (plan: PlanId) =>
	request<{ plan: PlanId; scheduled_plan: PlanId | null; effective_at: string }>('/billing/plan', {
		method: 'POST',
		body: { plan }
	});
export const billingCancel = () =>
	request<{ cancel_at: string }>('/billing/cancel', { method: 'POST' });
export const billingResume = () =>
	request<{ plan: PlanId; period_end: string }>('/billing/resume', { method: 'POST' });
/** Polar's customer portal; `payment_method` answers the same URL, as Polar has no deep link to the card (I-604). */
export const billingPortal = (what?: 'payment_method') =>
	request<{ url: string }>('/billing/portal', {
		method: 'POST',
		body: what ? { for: what } : undefined
	});
export const billingInvoices = () => request<Invoice[]>('/billing/invoices');

/** GET /public/seats, without a token: the landing page's count (I-290). */
export async function publicSeats(): Promise<PublicSeats> {
	const res = await fetch(`${baseUrl()}/public/seats`);
	if (!res.ok) throw new Error(`public/seats: ${res.status}`);
	return (await res.json()) as PublicSeats;
}

/** The build/apply log SSE URL, browser-usable with EventSource (5.3). */
export async function opLogUrl(
	projectId: string,
	opId: string,
	sinceSeq?: number
): Promise<string> {
	const token = await getAccessToken();
	const params = new URLSearchParams({ access_token: token });
	if (sinceSeq !== undefined) params.set('since', String(sinceSeq));
	return `${baseUrl()}/projects/${projectId}/ops/${opId}/log?${params}`;
}
