package cli

import (
	"context"
	"crypto/ed25519"
	"crypto/rand"
	"encoding/pem"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"golang.org/x/crypto/ssh"

	"github.com/heracraft/repose/internal/ca/sshca"
	"github.com/heracraft/repose/internal/ca/testca"
	fakeapi "github.com/heracraft/repose/internal/fakes/api"
)

func withHome(t *testing.T) string {
	t.Helper()
	home := t.TempDir()
	old := os.Getenv("HOME")
	_ = os.Setenv("HOME", home)
	t.Cleanup(func() { _ = os.Setenv("HOME", old) })
	return home
}

func testProjects() []Project {
	return []Project{
		{ID: "p1", Slug: "todo-app"},
		{ID: "p2", Slug: "blog"},
	}
}

func TestRenderSSHConfigGolden(t *testing.T) {
	got := renderSSHConfig(testProjects(), "heracraft", "~", true)
	want := `# Generated by repose; edits here are overwritten. ~/.ssh/repose/config includes this file.
Host blog.repose
  # project p2
  HostName ssh.repose.herakraft.co
  User blog.heracraft
  IdentityFile ~/.ssh/repose/id_ed25519
  CertificateFile ~/.ssh/repose/id_ed25519-cert.pub
  IdentitiesOnly yes
  UserKnownHostsFile ~/.ssh/repose/known_hosts
  ForwardAgent no
  ServerAliveInterval 30
  ControlMaster auto
  ControlPath ~/.ssh/repose/cm-%C
  ControlPersist 10m
Host todo-app.repose
  # project p1
  HostName ssh.repose.herakraft.co
  User todo-app.heracraft
  IdentityFile ~/.ssh/repose/id_ed25519
  CertificateFile ~/.ssh/repose/id_ed25519-cert.pub
  IdentitiesOnly yes
  UserKnownHostsFile ~/.ssh/repose/known_hosts
  ForwardAgent no
  ServerAliveInterval 30
  ControlMaster auto
  ControlPath ~/.ssh/repose/cm-%C
  ControlPersist 10m
`
	if got != want {
		t.Fatalf("renderSSHConfig mismatch:\ngot:\n%s\nwant:\n%s", got, want)
	}
	// Windows' OpenSSH has no multiplexing: the same blocks without it.
	win := renderSSHConfig(testProjects(), "heracraft", "~", false)
	if strings.Contains(win, "Control") {
		t.Fatalf("multiplexing lines in the non-multiplexed config:\n%s", win)
	}
	// I-247: the laptop's agent is never forwarded, and the explicit "no"
	// wins over a later `Host *` block with ForwardAgent yes.
	if strings.Contains(got, "ForwardAgent yes") || strings.Contains(win, "ForwardAgent yes") {
		t.Fatal("the generated config forwards the agent (I-247)")
	}
	if strings.Contains(got, "~/.ssh/id_ed25519") {
		t.Fatal("the user's own key must never appear in the generated config (I-149)")
	}
}

// TestEnsureCertMovesOffTheUsersKey is I-149: a certificate v0.1.4 issued
// for ~/.ssh/id_ed25519 (passphrase-protected on the owner's laptop, so
// every ssh prompted) is replaced by one for ~/.ssh/repose/id_ed25519,
// which the CLI generates without a passphrase, and the user's key is
// neither read into the request nor changed.
func TestEnsureCertMovesOffTheUsersKey(t *testing.T) {
	home := withHome(t)
	sd := filepath.Join(home, ".ssh", "repose")
	if err := os.MkdirAll(sd, 0o700); err != nil {
		t.Fatal(err)
	}
	userPriv, userPub, err := testKeyPair()
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(home, ".ssh", "id_ed25519"), userPriv, 0o600); err != nil {
		t.Fatal(err)
	}
	ca, err := testca.New()
	if err != nil {
		t.Fatal(err)
	}
	fake := fakeapi.New(fakeapi.Options{CA: ca})
	defer fake.Close()
	client := newClient(fake.URL()+"/v1", staticToken("tok"))
	p1, err := client.CreateProject(context.Background(), CreateProjectRequest{Name: "todo-app", Class: "large"})
	if err != nil {
		t.Fatal(err)
	}
	// Valid for hours and covering the project: only the key is wrong.
	old, err := ca.SignUserCert(userPub, "u:handle", []string{p1.ID}, sshca.UserCertTTL)
	if err != nil {
		t.Fatal(err)
	}
	oldLine := sshca.Marshal(old) + "\n"
	if err := os.WriteFile(filepath.Join(sd, "id_ed25519-cert.pub"), []byte(oldLine), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(sd, "known_hosts"), []byte("x\n"), 0o600); err != nil {
		t.Fatal(err)
	}

	res, err := ensureCert(context.Background(), client, certParams{Handle: "heracraft", Projects: []Project{*p1}}, nil)
	if err != nil {
		t.Fatalf("ensureCert: %v", err)
	}
	cert := parseCertFile(res.Path)
	if cert == nil {
		t.Fatal("no certificate written")
	}
	reposePub, err := ensureReposeKey()
	if err != nil {
		t.Fatal(err)
	}
	if !certIsFor(cert, reposePub) {
		t.Fatal("the new certificate is not for ~/.ssh/repose/id_ed25519")
	}
	info, err := os.Stat(filepath.Join(sd, "id_ed25519"))
	if err != nil || info.Mode().Perm() != 0o600 {
		t.Fatalf("repose key mode = %v, err %v; want 0600", info.Mode().Perm(), err)
	}
	b, _ := os.ReadFile(filepath.Join(sd, "id_ed25519"))
	if _, err := ssh.ParsePrivateKey(b); err != nil {
		t.Fatalf("the repose key must load without a passphrase: %v", err)
	}
	after, _ := os.ReadFile(filepath.Join(home, ".ssh", "id_ed25519"))
	if string(after) != string(userPriv) {
		t.Fatal("the user's own key changed")
	}
	if _, err := os.Stat(filepath.Join(home, ".ssh", "id_ed25519.pub")); err == nil {
		t.Fatal("ensureCert created a .pub next to the user's key")
	}
}

func testKeyPair() ([]byte, ssh.PublicKey, error) {
	_, sk, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		return nil, nil, err
	}
	block, err := ssh.MarshalPrivateKey(sk, "user")
	if err != nil {
		return nil, nil, err
	}
	signer, err := ssh.NewSignerFromKey(sk)
	if err != nil {
		return nil, nil, err
	}
	return pem.EncodeToMemory(block), signer.PublicKey(), nil
}

// TestIncludeEffective is I-151: an Include after a Host line, or
// commented out, does not count, and a fresh one goes on top.
func TestIncludeEffective(t *testing.T) {
	cases := map[string]bool{
		"":                               false,
		"Include ~/.ssh/repose/config\n": true,
		"# added by repose\nInclude ~/.ssh/repose/config\nHost x\n": true,
		"Host x\n  User y\nInclude ~/.ssh/repose/config\n":          false,
		"# Include ~/.ssh/repose/config\n":                          false,
		"include /home/a/.ssh/repose/config\n":                      true,
		"Match all\nInclude ~/.ssh/repose/config\n":                 false,
	}
	for content, want := range cases {
		if got := includeEffective(content); got != want {
			t.Errorf("includeEffective(%q) = %v, want %v", content, got, want)
		}
	}

	home := withHome(t)
	path := filepath.Join(home, ".ssh", "config")
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		t.Fatal(err)
	}
	misplaced := "Host example.com\n  User bob\nInclude ~/.ssh/repose/config\n"
	if err := os.WriteFile(path, []byte(misplaced), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := ensureIncludeLine(path); err != nil {
		t.Fatal(err)
	}
	b, _ := os.ReadFile(path)
	if !includeEffective(string(b)) || !strings.HasSuffix(string(b), misplaced) {
		t.Fatalf("misplaced Include not fixed by prepending:\n%s", b)
	}
}

// TestEnsureIncludeLineLeavesAReadOnlyLinkAlone is the home-manager case:
// ~/.ssh/config links into a read-only store. The CLI must not replace
// the link with a file of its own; it reports the target so the message
// can say where to add the line.
func TestEnsureIncludeLineLeavesAReadOnlyLinkAlone(t *testing.T) {
	if os.Getuid() == 0 {
		t.Skip("root writes through read-only modes")
	}
	home := withHome(t)
	store := filepath.Join(t.TempDir(), "store")
	if err := os.MkdirAll(store, 0o755); err != nil {
		t.Fatal(err)
	}
	target := filepath.Join(store, "ssh_config")
	if err := os.WriteFile(target, []byte("Host *\n  ServerAliveInterval 60\n"), 0o444); err != nil {
		t.Fatal(err)
	}
	if err := os.Chmod(store, 0o555); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = os.Chmod(store, 0o755) })
	path := filepath.Join(home, ".ssh", "config")
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		t.Fatal(err)
	}
	if err := os.Symlink(target, path); err != nil {
		t.Fatal(err)
	}
	err := ensureIncludeLine(path)
	var ro *includeUnwritableError
	if !errors.As(err, &ro) || ro.target != target {
		t.Fatalf("err = %v, want an includeUnwritableError naming %s", err, target)
	}
	if info, err := os.Lstat(path); err != nil || info.Mode()&os.ModeSymlink == 0 {
		t.Fatal("the link was replaced")
	}
	msg := includeProblemText(path, err)
	if !strings.Contains(msg, target) || !strings.Contains(msg, includeLine) {
		t.Fatalf("problem text does not say where and what: %s", msg)
	}
}

func TestEnsureIncludeLineOnceAndFirst(t *testing.T) {
	home := withHome(t)
	path := filepath.Join(home, ".ssh", "config")
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		t.Fatal(err)
	}
	preexisting := "Host example.com\n  User bob\n"
	if err := os.WriteFile(path, []byte(preexisting), 0o600); err != nil {
		t.Fatal(err)
	}

	if err := ensureIncludeLine(path); err != nil {
		t.Fatal(err)
	}
	b1, _ := os.ReadFile(path)
	lines := strings.Split(string(b1), "\n")
	if lines[0] != includeComment || lines[1] != includeLine {
		t.Fatalf("include not first two lines: %q", string(b1))
	}
	if !strings.Contains(string(b1), preexisting) {
		t.Fatalf("preexisting content lost: %q", string(b1))
	}

	// Running again must not duplicate or otherwise change anything.
	if err := ensureIncludeLine(path); err != nil {
		t.Fatal(err)
	}
	b2, _ := os.ReadFile(path)
	if string(b1) != string(b2) {
		t.Fatalf("second run changed the file:\nfirst:\n%s\nsecond:\n%s", b1, b2)
	}
	if strings.Count(string(b2), includeLine) != 1 {
		t.Fatalf("include line duplicated: %q", string(b2))
	}
}

func TestCertUsableFor(t *testing.T) {
	ca, err := testca.New()
	if err != nil {
		t.Fatal(err)
	}
	_, pub, err := sshca.GenerateHostKey("test")
	if err != nil {
		t.Fatal(err)
	}
	now := time.Now()
	cert, err := ca.SignUserCert(pub, "u:handle", []string{"p1", "p2"}, certReuseMargin+time.Hour)
	if err != nil {
		t.Fatal(err)
	}

	if !certUsableFor(cert, []string{"p1", "p2"}, now, certReuseMargin) {
		t.Fatal("should be usable: covers both ids, plenty of validity")
	}
	if certUsableFor(cert, []string{"p1", "p3"}, now, certReuseMargin) {
		t.Fatal("should not be usable: does not cover p3")
	}
	if certUsableFor(cert, []string{"p1"}, now.Add(110*time.Minute), certReuseMargin) {
		t.Fatal("should not be usable: less than the reuse margin remains")
	}
	if certUsableFor(nil, []string{"p1"}, now, certReuseMargin) {
		t.Fatal("nil cert is never usable")
	}
}

func TestEnsureCertReusesValidCertificate(t *testing.T) {
	home := withHome(t)
	sd := filepath.Join(home, ".ssh", "repose")
	if err := os.MkdirAll(sd, 0o700); err != nil {
		t.Fatal(err)
	}

	// Plant an identity key and a certificate that already covers both
	// projects with plenty of validity left.
	if _, err := ensureReposeKey(); err != nil {
		t.Fatal(err)
	}
	pubBytes, err := os.ReadFile(filepath.Join(home, ".ssh", "repose", "id_ed25519.pub"))
	if err != nil {
		t.Fatal(err)
	}
	pub, _, _, _, err := ssh.ParseAuthorizedKey(pubBytes)
	if err != nil {
		t.Fatal(err)
	}
	ca, err := testca.New()
	if err != nil {
		t.Fatal(err)
	}
	cert, err := ca.SignUserCert(pub, "u:handle", []string{"p1", "p2"}, sshca.UserCertTTL)
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(sd, "id_ed25519-cert.pub"), []byte(sshca.Marshal(cert)+"\n"), 0o600); err != nil {
		t.Fatal(err)
	}

	// Reuse needs the known_hosts a previous issue wrote.
	if err := os.WriteFile(filepath.Join(sd, "known_hosts"), []byte("@cert-authority ssh.repose.herakraft.co,10.64.* ssh-ed25519 AAAA\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	// A client that fails any request proves ensureCert made none.
	fake := fakeapi.New(fakeapi.Options{})
	defer fake.Close()
	fake.Fail("POST /certs", "internal")
	client := newClient(fake.URL()+"/v1", staticToken("tok"))
	// A reused certificate leaves a running master alone.
	if err := os.WriteFile(filepath.Join(sd, "cm-0123abcd"), nil, 0o600); err != nil {
		t.Fatal(err)
	}
	defer func(prev func(context.Context, string, string)) { muxStop = prev }(muxStop)
	muxStop = func(_ context.Context, _, alias string) { t.Errorf("master for %s stopped on reuse", alias) }

	res, err := ensureCert(context.Background(), client, certParams{Handle: "heracraft", Projects: testProjects()}, nil)
	if err != nil {
		t.Fatalf("ensureCert: %v", err)
	}
	certPath := res.Path
	if certPath != filepath.Join(sd, "id_ed25519-cert.pub") {
		t.Fatalf("unexpected cert path %q", certPath)
	}
	cfg, err := os.ReadFile(filepath.Join(sd, sshHostsName))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(cfg), "Host todo-app.repose") {
		t.Fatalf("ssh config missing project block: %s", cfg)
	}
}

func TestEnsureCertReissuesWhenProjectAdded(t *testing.T) {
	home := withHome(t)
	sd := filepath.Join(home, ".ssh", "repose")
	if err := os.MkdirAll(sd, 0o700); err != nil {
		t.Fatal(err)
	}
	if _, err := ensureReposeKey(); err != nil {
		t.Fatal(err)
	}
	pubBytes, _ := os.ReadFile(filepath.Join(home, ".ssh", "repose", "id_ed25519.pub"))
	pub, _, _, _, _ := ssh.ParseAuthorizedKey(pubBytes)

	fake := fakeapi.New(fakeapi.Options{})
	defer fake.Close()
	client := newClient(fake.URL()+"/v1", staticToken("tok"))
	ctx := context.Background()
	p1, err := client.CreateProject(ctx, CreateProjectRequest{Name: "todo-app", Class: "large"})
	if err != nil {
		t.Fatal(err)
	}
	p2, err := client.CreateProject(ctx, CreateProjectRequest{Name: "blog", Class: "large"})
	if err != nil {
		t.Fatal(err)
	}
	projects := []Project{*p1, *p2}

	ca, err := testca.New()
	if err != nil {
		t.Fatal(err)
	}
	// Existing cert covers only p1; the account now also has p2, so
	// certUsableFor must say no and ensureCert must call the api again.
	old, err := ca.SignUserCert(pub, "u:handle", []string{p1.ID}, sshca.UserCertTTL)
	if err != nil {
		t.Fatal(err)
	}
	oldLine := sshca.Marshal(old) + "\n"
	if err := os.WriteFile(filepath.Join(sd, "id_ed25519-cert.pub"), []byte(oldLine), 0o600); err != nil {
		t.Fatal(err)
	}
	// A master left from the old certificate is asked to stop for every
	// project (I-436), so later commands start one with the new certificate.
	if err := os.WriteFile(filepath.Join(sd, "cm-0123abcd"), nil, 0o600); err != nil {
		t.Fatal(err)
	}
	var stopped []string
	defer func(prev func(context.Context, string, string)) { muxStop = prev }(muxStop)
	muxStop = func(_ context.Context, _, alias string) { stopped = append(stopped, alias) }

	res, err := ensureCert(ctx, client, certParams{Handle: "heracraft", Projects: projects}, nil)
	if got := strings.Join(stopped, ","); got != p1.Slug+".repose,"+p2.Slug+".repose" {
		t.Fatalf("masters stopped: %q", got)
	}
	if err != nil {
		t.Fatalf("ensureCert: %v", err)
	}
	certPath := res.Path
	newBytes, err := os.ReadFile(certPath)
	if err != nil {
		t.Fatal(err)
	}
	// The fake api's canned certificate text is not itself a parseable
	// certificate (docs/interfaces "Fake" makes no promise about its
	// bytes, only that IssueCert was called); what this test proves is
	// that certUsableFor's rejection of the stale cert drove ensureCert
	// to call the api again and overwrite the file, not reuse it.
	if string(newBytes) == oldLine {
		t.Fatal("ensureCert reused a certificate that does not cover the new project")
	}
}
