package cli

import (
	"context"
	"errors"
	"strings"
	"testing"

	fakeapi "github.com/heracraft/repose/internal/fakes/api"
)

func menuOf(t *testing.T, e *Env, id string) []MenuItem {
	t.Helper()
	cfg, err := e.Client.GetConfig(context.Background(), id)
	if err != nil {
		t.Fatal(err)
	}
	sel, err := currentMenu(cfg)
	if err != nil {
		t.Fatal(err)
	}
	return sel
}

func exitCode(err error) int {
	var ee *exitError
	if errors.As(err, &ee) {
		return ee.code
	}
	return -1
}

// `repose config add` takes catalog ids and any nixpkgs attribute, prints
// one short line before the build, and `remove` takes them out again
// (DECISIONS I-220).
func TestConfigAddAndRemove(t *testing.T) {
	fake := fakeapi.New(fakeapi.Options{})
	defer fake.Close()
	e, p := newRoundtripEnv(t, fake)
	ctx := context.Background()
	out := &discardWriter{}
	e.Out = out

	if err := ConfigAddCmd(ctx, e, "", []string{"gcc", "air"}); err != nil {
		t.Fatalf("add: %v", err)
	}
	if got := out.buf.String(); !strings.HasPrefix(got, "Added gcc and air to todo-app. Building revision ") || !strings.Contains(got, "Applied revision ") {
		t.Fatalf("add output:\n%s", got)
	}
	cfg, _ := e.Client.GetConfig(ctx, p.ID)
	if !strings.Contains(cfg.Fragment, `(nixpkg [ "air" ])`) || !strings.Contains(cfg.Fragment, `(nixpkg [ "gcc" ])`) {
		t.Fatalf("fragment:\n%s", cfg.Fragment)
	}

	// A catalog id is the catalog entry; pkgs./nixpkgs# prefixes are
	// dropped; a dotted attribute path is a package; a repeat is named.
	out.buf.Reset()
	if err := ConfigAddCmd(ctx, e, "", []string{"bun", "nixpkgs#python312Packages.black", "pkgs.gcc"}); err != nil {
		t.Fatalf("add 2: %v", err)
	}
	if got := out.buf.String(); !strings.HasPrefix(got, "gcc is already in todo-app.\nAdded bun and python312Packages.black to todo-app. Building revision ") {
		t.Fatalf("add 2 output:\n%s", got)
	}
	sel := menuOf(t, e, p.ID)
	want := []MenuItem{{Package: "gcc"}, {Package: "air"}, {ID: "bun"}, {Package: "python312Packages.black"}}
	if len(sel) != len(want) {
		t.Fatalf("selection %+v", sel)
	}
	for i := range want {
		if sel[i].ID != want[i].ID || sel[i].Package != want[i].Package {
			t.Fatalf("selection %+v, want %+v", sel, want)
		}
	}

	// Nothing new: no build.
	out.buf.Reset()
	if err := ConfigAddCmd(ctx, e, "", []string{"gcc", "bun"}); err != nil {
		t.Fatalf("add again: %v", err)
	}
	if got := out.buf.String(); got != "gcc and bun are already in todo-app.\n" {
		t.Fatalf("add again output: %q", got)
	}

	// Names that are not attribute paths never reach the api.
	for _, bad := range []string{"a;b", "${x}", "../x", `"gcc"`, "g cc", ""} {
		err := ConfigAddCmd(ctx, e, "", []string{bad})
		if exitCode(err) != ExitUsage || !strings.Contains(err.Error(), "is not a nixpkgs attribute name") {
			t.Fatalf("%q: %v", bad, err)
		}
	}

	out.buf.Reset()
	if err := ConfigRemoveCmd(ctx, e, "", []string{"air", "bun", "zig"}); err != nil {
		t.Fatalf("remove: %v", err)
	}
	if got := out.buf.String(); !strings.HasPrefix(got, "zig is not in todo-app's menu.\nRemoved air and bun from todo-app. Building revision ") {
		t.Fatalf("remove output:\n%s", got)
	}
	sel = menuOf(t, e, p.ID)
	if len(sel) != 2 || sel[0].Package != "gcc" || sel[1].Package != "python312Packages.black" {
		t.Fatalf("after remove: %+v", sel)
	}
	if err := ConfigRemoveCmd(ctx, e, "", []string{"zig"}); exitCode(err) != ExitUsage {
		t.Fatalf("remove of an absent name: %v", err)
	}
	// Down to nothing: an empty menu, still menu mode.
	if err := ConfigRemoveCmd(ctx, e, "", []string{"gcc", "python312Packages.black"}); err != nil {
		t.Fatalf("remove all: %v", err)
	}
	cfg, _ = e.Client.GetConfig(ctx, p.ID)
	if sel := menuOf(t, e, p.ID); len(sel) != 0 || cfg.Menu == nil || !strings.HasPrefix(cfg.Fragment, "# generated by repose") {
		t.Fatalf("after remove all: %+v\n%s", sel, cfg.Fragment)
	}
	if err := ConfigAddCmd(ctx, e, "", []string{"gcc"}); err != nil {
		t.Fatalf("add after empty: %v", err)
	}
}

// A failed build says so in one line and exits 10; a hand-written
// fragment turns the menu off with a pointer to config edit.
func TestConfigAddFailures(t *testing.T) {
	fake := fakeapi.New(fakeapi.Options{})
	defer fake.Close()
	e, _ := newRoundtripEnv(t, fake)
	ctx := context.Background()
	out := &discardWriter{}
	e.Out = out

	// The fake fails any fragment carrying its marker, a valid attribute name.
	err := ConfigAddCmd(ctx, e, "", []string{"repose-force-eval-error"})
	if exitCode(err) != ExitBuildFailed {
		t.Fatalf("failed build: %v", err)
	}
	if got := out.buf.String(); !strings.Contains(got, "Nothing changed in todo-app; the previous revision is still active.") || strings.Contains(got, "fragment.nix:") {
		t.Fatalf("failed build output:\n%s", got)
	}

	if err := ConfigApplyCmd(ctx, e, "", writeTempFragment(t, "{ pkgs, ... }: { home.packages = [ pkgs.ripgrep ]; }")); err != nil {
		t.Fatal(err)
	}
	err = ConfigAddCmd(ctx, e, "", []string{"gcc"})
	if exitCode(err) != ExitUsage || !strings.Contains(err.Error(), "repose.nix was written by hand") || !strings.Contains(err.Error(), "repose config edit") {
		t.Fatalf("custom fragment: %v", err)
	}
	err = ConfigRemoveCmd(ctx, e, "", []string{"gcc"})
	if exitCode(err) != ExitUsage || !strings.Contains(err.Error(), "repose.nix was written by hand") {
		t.Fatalf("remove on custom fragment: %v", err)
	}
}

func TestMenuNameAndJoin(t *testing.T) {
	for in, want := range map[string]string{"gcc": "gcc", "pkgs.gcc": "gcc", "nixpkgs#air": "air", " python312Packages.black ": "python312Packages.black"} {
		if got := menuName(in); got != want {
			t.Errorf("menuName(%q) = %q", in, got)
		}
	}
	for _, c := range []struct {
		in   []string
		want string
	}{{[]string{"gcc"}, "gcc"}, {[]string{"gcc", "air"}, "gcc and air"}, {[]string{"gcc", "air", "zig"}, "gcc, air and zig"}} {
		if got := joinNames(c.in); got != c.want {
			t.Errorf("joinNames(%v) = %q", c.in, got)
		}
	}
	if shortRev("0123456789abcdef") != "89abcdef" {
		t.Error(shortRev("0123456789abcdef"))
	}
	if got := genLocRe.ReplaceAllString(`nixpkgs has no package "foo"; search https://search.nixos.org/packages at fragment.nix:11:23`, ""); got != `nixpkgs has no package "foo"; search https://search.nixos.org/packages` {
		t.Error(got)
	}
}
