package cli

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/http/httptest"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"sync"
	"testing"
	"time"

	"github.com/heracraft/repose/internal/ca/sshca"
	"github.com/heracraft/repose/internal/ca/testca"
	fakeapi "github.com/heracraft/repose/internal/fakes/api"
	"github.com/heracraft/repose/internal/testguest"
)

func TestRenderSSHEntry(t *testing.T) {
	got := renderSSHEntry("/home/u/.local/bin/repose", "~")
	want := `# Generated by repose; edits here are overwritten.
# Before ssh reads the Host blocks, repose renews the certificate and adds
# the block of a project this laptop has not connected to yet.
Match originalhost "*.repose,!*'*" exec "'/home/u/.local/bin/repose' ssh-prepare '%n'"
Match all
Include ~/.ssh/repose/hosts
`
	if got != want {
		t.Fatalf("entry:\n%s\nwant:\n%s", got, want)
	}
	// A path the Match line cannot carry safely, and no binary at all
	// (the test binary): the Include alone, as before I-281.
	for _, exe := range []string{"/Users/o'brien/bin/repose", `C:\x\repose.exe`, "/opt/100%/repose", ""} {
		if got := renderSSHEntry(exe, "~"); strings.Contains(got, "Match") || !strings.Contains(got, "Include ~/.ssh/repose/hosts") {
			t.Errorf("%q:\n%s", exe, got)
		}
	}
	if got := renderSSHEntry("/r/repose", "/Users/Jo Smith"); !strings.Contains(got, `Include "/Users/Jo Smith/.ssh/repose/hosts"`) {
		t.Errorf("home with a space:\n%s", got)
	}
	t.Setenv("REPOSE_TEST_GOOS", "windows")
	if got := renderSSHEntry("/r/repose", "~"); strings.Contains(got, "Match") {
		t.Errorf("windows:\n%s", got)
	}
}

func TestSSHPrepareRefusesANonProjectHost(t *testing.T) {
	err := sshPrepare(context.Background(), "github.com", func() (*Env, error) { t.Fatal("no env for a refused host"); return nil, nil })
	if err == nil || exitCodeFor(err, &strings.Builder{}) != ExitUsage {
		t.Fatalf("err = %v", err)
	}
}

// plainSSHFixture is a laptop that used repose for todo-app yesterday: its
// ~/.ssh/repose has the entry config the built binary writes, a Host
// block for todo-app only, and a certificate for todo-app only that has
// expired. blog was created since, on another laptop. The "gateway" is a
// fake guest that checks the certificate like the real one: signed by
// the api's user CA, carrying the project id the login names.
type plainSSHFixture struct {
	home, bin, top string
	guest          *testguest.Guest
	env            []string
	calls          func(string) int
	todo, blog     *Project
	sd             string
}

func newPlainSSHFixture(t *testing.T) *plainSSHFixture {
	t.Helper()
	if testing.Short() {
		t.Skip("builds the CLI and runs the system's ssh, scp, rsync and git")
	}
	for _, tool := range []string{"ssh", "scp", "rsync", "git"} {
		if _, err := exec.LookPath(tool); err != nil {
			t.Skipf("%s not installed", tool)
		}
	}
	f := &plainSSHFixture{}
	f.bin = filepath.Join(t.TempDir(), "repose")
	build := exec.Command("go", "build", "-o", f.bin, "../../cmd/repose")
	build.Env = append(filterTestEnv(os.Environ(), "HOME", "XDG_CONFIG_HOME"), "HOME="+realHome, "CGO_ENABLED=0")
	if out, err := build.CombinedOutput(); err != nil {
		t.Fatalf("go build: %v\n%s", err, out)
	}

	ca, err := testca.New()
	if err != nil {
		t.Fatal(err)
	}
	fake := fakeapi.New(fakeapi.Options{CA: ca})
	t.Cleanup(fake.Close)
	var mu sync.Mutex
	counts := map[string]int{}
	api := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		mu.Lock()
		counts[r.Method+" "+r.URL.Path]++
		mu.Unlock()
		fake.ServeHTTP(w, r)
	}))
	t.Cleanup(api.Close)
	f.calls = func(k string) int { mu.Lock(); defer mu.Unlock(); return counts[k] }

	client := newClient(fake.URL()+"/v1", staticToken("tok"))
	ctx := context.Background()
	if f.todo, err = client.CreateProject(ctx, CreateProjectRequest{Name: "todo-app", Class: "large"}); err != nil {
		t.Fatal(err)
	}
	if f.blog, err = client.CreateProject(ctx, CreateProjectRequest{Name: "blog", Class: "large"}); err != nil {
		t.Fatal(err)
	}
	handle := fakeapi.CannedUser.Handle

	guestHome := t.TempDir()
	logins := map[string]string{"todo-app." + handle: f.todo.ID, "blog." + handle: f.blog.ID}
	f.guest, err = testguest.NewWithCA(guestHome, ca.User.Signer.PublicKey(), func(login string) string { return logins[login] })
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(f.guest.Close)
	checkout := filepath.Join(guestHome, "blog")
	mustRun(t, "", "git", "init", "-q", "-b", "main", checkout)
	if err := os.WriteFile(filepath.Join(checkout, "notes.txt"), []byte("written in the guest\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	mustRun(t, checkout, "git", "add", ".")
	mustRun(t, checkout, "git", "-c", "user.name=t", "-c", "user.email=t@example.com", "commit", "-q", "-m", "first")

	f.home = withHome(t)
	t.Setenv("XDG_CONFIG_HOME", filepath.Join(f.home, ".config"))
	cfgDir := filepath.Join(f.home, ".config", "repose")
	creds, _ := json.Marshal(Credentials{AccessToken: "tok", ExpiresAt: time.Now().Add(24 * time.Hour), LogtoIssuer: "https://auth.example"})
	if err := writeFileAtomic(filepath.Join(cfgDir, "credentials.json"), creds, 0o600); err != nil {
		t.Fatal(err)
	}

	// Yesterday's files: what the binary writes, for todo-app alone.
	f.sd, err = sshDir()
	if err != nil {
		t.Fatal(err)
	}
	pub, err := ensureReposeKey()
	if err != nil {
		t.Fatal(err)
	}
	old, err := ca.User.SignUser(sshca.UserCert{PublicKey: pub, KeyID: "u:" + handle, Principals: []string{f.todo.ID}, Serial: 1,
		ValidAfter: time.Now().Add(-25 * time.Hour), ValidBefore: time.Now().Add(-time.Hour)})
	if err != nil {
		t.Fatal(err)
	}
	for name, body := range map[string]string{
		"id_ed25519-cert.pub": sshca.Marshal(old) + "\n",
		"known_hosts":         fmt.Sprintf("@cert-authority %s %s\n", gatewayHost, ca.Host.PublicLine()),
		sshHostsName:          renderSSHConfig([]Project{*f.todo}, handle, sshPathPrefix(), true),
		"config":              renderSSHEntry(f.bin, sshPathPrefix()),
	} {
		if err := writeFileAtomic(filepath.Join(f.sd, name), []byte(body), 0o600); err != nil {
			t.Fatal(err)
		}
	}

	// ssh reads ~/.ssh/config from the passwd entry, not $HOME, so the
	// test's stands in for it: the gateway's address (a user's would come
	// from the Host block), then exactly the Include line the CLI adds.
	host, port, _ := strings.Cut(f.guest.Addr, ":")
	f.top = filepath.Join(f.home, "ssh-config-standing-in-for-the-users")
	top := fmt.Sprintf(`Host *.repose
  HostName %s
  Port %s
  StrictHostKeyChecking no
  UserKnownHostsFile /dev/null
  ControlMaster no
  ControlPath none
  LogLevel ERROR
Match all
Include %s
`, host, port, filepath.Join(f.sd, "config"))
	if err := os.WriteFile(f.top, []byte(top), 0o600); err != nil {
		t.Fatal(err)
	}
	f.env = append(filterTestEnv(os.Environ(), envSSHPrepared, envAPIURL, "GIT_SSH_COMMAND"),
		envAPIURL+"="+api.URL+"/v1")
	return f
}

// run runs a command with the fixture's environment and returns its
// combined output.
func (f *plainSSHFixture) run(t *testing.T, dir string, env []string, name string, args ...string) (string, error) {
	t.Helper()
	cmd := exec.Command(name, args...)
	cmd.Dir = dir
	cmd.Env = append(append([]string(nil), f.env...), env...)
	out, err := cmd.CombinedOutput()
	return string(out), err
}

// TestPlainSSHToAProjectNeverRunHere is I-281 end to end: the system's
// ssh, scp, rsync and git reach blog, whose Host block was never written
// on this laptop, with an expired certificate, and no repose command run
// first. The Match line in ~/.ssh/repose/config runs the built binary,
// which asks the api, writes blog's block and a new certificate, and the
// same ssh then reads them.
func TestPlainSSHToAProjectNeverRunHere(t *testing.T) {
	f := newPlainSSHFixture(t)
	if hosts, _ := os.ReadFile(filepath.Join(f.sd, sshHostsName)); strings.Contains(string(hosts), "blog.repose") {
		t.Fatal("the fixture already has blog's block")
	}

	out, err := f.run(t, "", nil, "ssh", "-F", f.top, "blog.repose", "echo hello from $(basename $PWD); cat blog/notes.txt")
	t.Logf("$ ssh blog.repose ...\n%s", out)
	if err != nil || !strings.Contains(out, "written in the guest") {
		t.Fatalf("ssh: %v\n%s", err, out)
	}
	hosts, _ := os.ReadFile(filepath.Join(f.sd, sshHostsName))
	if !strings.Contains(string(hosts), "Host blog.repose") {
		t.Fatalf("no block for blog after the ssh:\n%s", hosts)
	}
	cert := parseCertFile(filepath.Join(f.sd, reposeKeyName+"-cert.pub"))
	if !certUsableFor(cert, []string{f.todo.ID, f.blog.ID}, time.Now(), time.Hour) {
		t.Fatalf("certificate after the ssh: %+v", cert)
	}
	issued := f.calls("POST /v1/certs")
	if issued != 1 {
		t.Fatalf("POST /certs %d times, want 1", issued)
	}

	local := t.TempDir()
	// The fake guest has no sftp subsystem: the classic protocol, which is
	// scp's default before OpenSSH 9.0 (whose scp has no -O).
	scpArgs := []string{"-F", f.top, "blog.repose:blog/notes.txt", filepath.Join(local, "via-scp.txt")}
	if probe, _ := exec.Command("scp", "-O").CombinedOutput(); !strings.Contains(string(probe), "unknown option") {
		scpArgs = append([]string{"-O"}, scpArgs...)
	}
	out, err = f.run(t, "", nil, "scp", scpArgs...)
	t.Logf("$ scp -O blog.repose:blog/notes.txt .\n%s", out)
	if b, _ := os.ReadFile(filepath.Join(local, "via-scp.txt")); err != nil || string(b) != "written in the guest\n" {
		t.Fatalf("scp: %v %q\n%s", err, b, out)
	}
	out, err = f.run(t, "", nil, "rsync", "-a", "-e", "ssh -F "+f.top, "blog.repose:blog/notes.txt", filepath.Join(local, "via-rsync.txt"))
	t.Logf("$ rsync -a -e ssh blog.repose:blog/notes.txt .\n%s", out)
	if b, _ := os.ReadFile(filepath.Join(local, "via-rsync.txt")); err != nil || string(b) != "written in the guest\n" {
		t.Fatalf("rsync: %v %q\n%s", err, b, out)
	}
	out, err = f.run(t, "", []string{"GIT_SSH_COMMAND=ssh -F " + f.top}, "git", "ls-remote", "blog.repose:blog")
	t.Logf("$ git ls-remote blog.repose:blog\n%s", out)
	if err != nil || !strings.Contains(out, "refs/heads/main") {
		t.Fatalf("git ls-remote: %v\n%s", err, out)
	}
	cloned := filepath.Join(local, "clone")
	out, err = f.run(t, "", []string{"GIT_SSH_COMMAND=ssh -F " + f.top}, "git", "clone", "-q", "blog.repose:blog", cloned)
	if b, _ := os.ReadFile(filepath.Join(cloned, "notes.txt")); err != nil || string(b) != "written in the guest\n" {
		t.Fatalf("git clone: %v %q\n%s", err, b, out)
	}
	// todo-app's block was there all along; its certificate is the new one.
	out, err = f.run(t, "", nil, "ssh", "-F", f.top, "todo-app.repose", "true")
	if err != nil {
		t.Fatalf("ssh todo-app.repose: %v\n%s", err, out)
	}
	if got := f.calls("POST /v1/certs"); got != issued {
		t.Fatalf("POST /certs %d times after the files were ready, want %d", got, issued)
	}

	// The fast path: files ready, no api call, and quick.
	before := f.calls("GET /v1/me") + f.calls("GET /v1/projects")
	start := time.Now()
	for i := 0; i < 10; i++ {
		if out, err := f.run(t, "", nil, f.bin, "ssh-prepare", "blog.repose"); err != nil {
			t.Fatalf("ssh-prepare: %v\n%s", err, out)
		}
	}
	each := time.Since(start) / 10
	t.Logf("ssh-prepare with the files ready: %s per run", each.Round(time.Millisecond))
	if got := f.calls("GET /v1/me") + f.calls("GET /v1/projects"); got != before {
		t.Fatalf("the fast path called the api (%d reads, was %d)", got, before)
	}
	if each > 500*time.Millisecond {
		t.Errorf("ssh-prepare took %s with nothing to do", each)
	}
}

// Several connections at once from an empty state (an editor opening its
// windows): every one connects and the certificate is issued once.
func TestPlainSSHConcurrentConnectionsIssueOnce(t *testing.T) {
	f := newPlainSSHFixture(t)
	var wg sync.WaitGroup
	errs := make([]error, 6)
	outs := make([]string, 6)
	for i := range errs {
		wg.Add(1)
		go func(i int) {
			defer wg.Done()
			outs[i], errs[i] = f.run(t, "", nil, "ssh", "-F", f.top, "blog.repose", "true")
		}(i)
	}
	wg.Wait()
	for i, err := range errs {
		if err != nil {
			t.Errorf("connection %d: %v\n%s", i, err, outs[i])
		}
	}
	if got := f.calls("POST /v1/certs"); got != 1 {
		t.Fatalf("POST /certs %d times for 6 concurrent connections, want 1", got)
	}
}

// Not logged in, nothing usable on disk: one line naming `repose login`,
// and ssh fails instead of waiting for anything.
func TestPlainSSHNotLoggedIn(t *testing.T) {
	f := newPlainSSHFixture(t)
	if err := os.Remove(filepath.Join(f.home, ".config", "repose", "credentials.json")); err != nil {
		t.Fatal(err)
	}
	start := time.Now()
	out, err := f.run(t, "", nil, "ssh", "-F", f.top, "blog.repose", "true")
	t.Logf("$ ssh blog.repose true   (logged out)\n%s", out)
	if err == nil || !strings.Contains(out, "Run `repose login`") {
		t.Fatalf("err = %v\n%s", err, out)
	}
	if took := time.Since(start); took > 10*time.Second {
		t.Fatalf("took %s", took)
	}
	out, err = f.run(t, "", nil, "ssh", "-F", f.top, "nosuch.repose", "true")
	t.Logf("$ ssh nosuch.repose true   (logged out)\n%s", out)
	if err == nil {
		t.Fatal("connected to a project that does not exist")
	}
}

func TestPlainSSHUnknownProject(t *testing.T) {
	f := newPlainSSHFixture(t)
	out, err := f.run(t, "", nil, "ssh", "-F", f.top, "nosuch.repose", "true")
	t.Logf("$ ssh nosuch.repose true\n%s", out)
	if err == nil || !strings.Contains(out, "No repose project is called nosuch.") {
		t.Fatalf("err = %v\n%s", err, out)
	}
}
