package cli

import (
	"context"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"os/user"
	"path/filepath"
	"regexp"
	"strings"
	"time"

	"github.com/spf13/cobra"
)

// Plain ssh to every project (DECISIONS I-281). ~/.ssh/repose/config, the
// file ~/.ssh/config includes, is two directives and an Include:
//
//	Match originalhost "*.repose,!*'*" exec "'/path/to/repose' ssh-prepare '%n'"
//	Match all
//	Include ~/.ssh/repose/hosts
//
// ssh evaluates the Match (running the command) before it reads the next
// line, and opens the included file only when it reaches the Include, so
// whatever `repose ssh-prepare` writes to ~/.ssh/repose/hosts is what this
// connection reads: a project created on another laptop gets its Host
// block, and an expired certificate is renewed, before ssh looks for
// either. Checked with OpenSSH 8.2, 8.8, 9.6 and 10.5. The Include is
// unconditional, so a prepare that fails (or a repose binary that moved)
// leaves ssh with the blocks already on disk, which is the behaviour
// before I-281. `!*'*` keeps a host name with a single quote out of the
// shell command (OpenSSH before 9.6 passes such names through).

// sshHostsName is the file with one Host block per project.
const sshHostsName = "hosts"

// envSSHPrepared is set by the CLI for its own children: an ssh the CLI
// runs has had its files prepared already, and `ssh-prepare` returns at
// once instead of taking the lock the CLI may hold (ensureCert's `ssh -G`
// would otherwise wait on itself).
const envSSHPrepared = "REPOSE_SSH_PREPARED"

// inheritedSSHPrepared is envSSHPrepared as this process received it,
// captured before Execute sets it for the children.
var inheritedSSHPrepared bool

// markSSHPrepared records the inherited value and sets the variable for
// every child from here on. Children that are not repose's own ssh (an
// editor `repose code` starts) get an environment without it.
func markSSHPrepared() {
	inheritedSSHPrepared = os.Getenv(envSSHPrepared) == "1"
	_ = os.Setenv(envSSHPrepared, "1")
}

// envWithoutSSHPrepared is os.Environ() minus envSSHPrepared, for a child
// that will run ssh on its own later (an editor).
func envWithoutSSHPrepared() []string {
	var out []string
	for _, kv := range os.Environ() {
		if strings.HasPrefix(kv, envSSHPrepared+"=") {
			continue
		}
		out = append(out, kv)
	}
	return out
}

// sshPathPrefix is how the generated files spell the home directory: "~"
// when ssh's own idea of home (the passwd entry, which is what ssh expands
// "~" to) is $HOME, else $HOME spelled out, so the files still point at
// the directory the CLI wrote to (tests, `sudo -E`, a relocated HOME).
func sshPathPrefix() string {
	home, err := os.UserHomeDir()
	if err != nil || goos() == "windows" {
		return "~"
	}
	u, err := user.Current()
	if err != nil || u.HomeDir == "" || filepath.Clean(u.HomeDir) == filepath.Clean(home) {
		return "~"
	}
	return home
}

// sshPath joins prefix and the path under home for a config line, quoted
// when it has a space.
func sshPath(prefix, rel string) string {
	p := prefix + "/" + rel
	if strings.ContainsAny(p, " \t") {
		return `"` + p + `"`
	}
	return p
}

// reposeExecutable is the path the Match line runs. The PATH entry is
// preferred when it is the same file as the running binary: an install
// that replaces the file in place (install.sh's ~/.local/bin, a
// package-manager symlink such as ~/.nix-profile/bin) keeps that path
// across upgrades, while the resolved target (a versioned store or
// Cellar directory) goes away with the old version.
//
// A binary not called repose (the package's test binary) gets no Match
// line: ssh would run it, and a test binary runs its whole suite.
func reposeExecutable() string {
	exe, err := os.Executable()
	if err != nil {
		return ""
	}
	if name := strings.TrimSuffix(filepath.Base(exe), ".exe"); name != "repose" {
		return ""
	}
	if onPath, err := exec.LookPath("repose"); err == nil {
		if abs, err := filepath.Abs(onPath); err == nil {
			a, errA := os.Stat(abs)
			b, errB := os.Stat(exe)
			if errA == nil && errB == nil && os.SameFile(a, b) {
				return abs
			}
		}
	}
	return exe
}

// matchLine is the Match directive for exe, or "" when exe cannot be
// written into it safely (a quote, backslash or % in the path; Windows,
// whose ssh runs the command through cmd.exe and where the CLI is not
// supported): ssh then reads the Host blocks on disk as before I-281.
func matchLine(exe string) string {
	if exe == "" || goos() == "windows" || strings.ContainsAny(exe, "'\"\\%\n\r") {
		return ""
	}
	return fmt.Sprintf(`Match originalhost "*.repose,!*'*" exec "'%s' ssh-prepare '%%n'"`, exe)
}

// renderSSHEntry is ~/.ssh/repose/config.
func renderSSHEntry(exe, prefix string) string {
	var b strings.Builder
	b.WriteString("# Generated by repose; edits here are overwritten.\n")
	if m := matchLine(exe); m != "" {
		b.WriteString("# Before ssh reads the Host blocks, repose renews the certificate and adds\n")
		b.WriteString("# the block of a project this laptop has not connected to yet.\n")
		b.WriteString(m + "\n")
		b.WriteString("Match all\n")
	}
	_, _ = fmt.Fprintf(&b, "Include %s\n", sshPath(prefix, ".ssh/repose/"+sshHostsName))
	return b.String()
}

// writeSSHEntry writes ~/.ssh/repose/config when it differs from what this
// binary would write. It needs no api call, so login writes it too.
func writeSSHEntry(sd string) error {
	want := renderSSHEntry(reposeExecutable(), sshPathPrefix())
	path := filepath.Join(sd, "config")
	if have, err := os.ReadFile(path); err == nil && string(have) == want {
		return nil
	}
	return writeFileAtomic(path, []byte(want), 0o600)
}

// sshEntryCurrent reports whether ~/.ssh/repose/config is what this binary
// would write: one from before I-281 (the Host blocks themselves), or one
// naming a repose binary that moved, is not.
func sshEntryCurrent(sd string) bool {
	have, err := os.ReadFile(filepath.Join(sd, "config"))
	return err == nil && string(have) == renderSSHEntry(reposeExecutable(), sshPathPrefix())
}

var prepareHostRe = regexp.MustCompile(`^[a-z0-9][a-z0-9-]*\.repose$`)

// sshReady is the prepare's fast path: the Host block for slug is on disk
// with its project id, the certificate for the CLI's key carries that id
// with margin left, and known_hosts is there. No api call, no lock.
func sshReady(sd, slug string, now time.Time, margin time.Duration) bool {
	hosts, err := os.ReadFile(filepath.Join(sd, sshHostsName))
	if err != nil {
		return false
	}
	id, ok := hostBlockProjectID(string(hosts), slug)
	if !ok {
		return false
	}
	if _, ok := hostBlockHandle(string(hosts), slug); !ok {
		return false
	}
	if _, err := os.Stat(filepath.Join(sd, "known_hosts")); err != nil {
		return false
	}
	pub, err := ensureReposeKey()
	if err != nil {
		return false
	}
	cert := parseCertFile(filepath.Join(sd, reposeKeyName+"-cert.pub"))
	return certIsFor(cert, pub) && certUsableFor(cert, []string{id}, now, margin)
}

// hostBlockProjectID reads the `# project <id>` line renderSSHConfig puts
// in each block.
func hostBlockProjectID(cfg, slug string) (string, bool) {
	in := false
	for _, l := range strings.Split(cfg, "\n") {
		t := strings.TrimSpace(l)
		if k, v, ok := strings.Cut(t, " "); ok && strings.EqualFold(k, "Host") {
			in = v == slug+".repose"
			continue
		}
		if in {
			if id, ok := strings.CutPrefix(t, "# project "); ok && id != "" {
				return id, true
			}
		}
	}
	return "", false
}

// prepareTimeout bounds the api calls of one prepare: an editor waits on
// it before its ssh even starts.
const prepareTimeout = 10 * time.Second

// sshPrepare is `repose ssh-prepare <host>`: make ~/.ssh/repose ready for
// an ssh to host, which is `<slug>.repose` as the user typed it. Messages
// go to stderr, which ssh passes through; nothing ever prompts.
func sshPrepare(ctx context.Context, host string, newEnvFn func() (*Env, error)) error {
	if inheritedSSHPrepared {
		return nil // the CLI's own ssh: prepared by the command that runs it
	}
	host = strings.ToLower(host)
	if !prepareHostRe.MatchString(host) {
		return exitf(ExitUsage, "repose: %q is not a project host; they look like todo-app.repose.", host)
	}
	slug := strings.TrimSuffix(host, ".repose")
	sd, err := sshDir()
	if err != nil {
		return err
	}
	if sshReady(sd, slug, time.Now(), certReuseMargin) {
		return nil
	}

	// Concurrent connections (an editor opens several at once) queue here;
	// the first renews, the rest find the files ready.
	unlock, err := lockFile(filepath.Join(sd, ".prepare.lock"))
	if err != nil {
		return err
	}
	defer unlock()
	if sshReady(sd, slug, time.Now(), certReuseMargin) {
		return nil
	}
	// The Env is read after the lock: a login refresh another prepare did
	// while this one waited rotated the refresh token on disk.
	e, err := newEnvFn()
	if err != nil {
		return err
	}
	ctx, cancel := context.WithTimeout(ctx, prepareTimeout)
	defer cancel()
	err = prepareFiles(ctx, e, slug)
	if err == nil {
		return nil
	}
	// A certificate still valid for a while is better than no connection:
	// say why it was not renewed and let ssh go on.
	if sshReady(sd, slug, time.Now(), time.Minute) {
		_, _ = fmt.Fprintf(os.Stderr, "repose: could not renew the SSH certificate (%v); using the one on disk.\n", briefErr(err))
		return nil
	}
	return err
}

// prepareFiles reads the account and its projects and has ensureCert write
// the certificate and every Host block.
func prepareFiles(ctx context.Context, e *Env, slug string) error {
	var me *Me
	var meErr error
	done := make(chan struct{})
	go func() {
		defer close(done)
		me, meErr = e.Client.GetMe(ctx)
	}()
	projects, err := e.Client.ListProjects(ctx)
	<-done
	if meErr != nil {
		return meErr
	}
	if err != nil {
		return err
	}
	found := false
	for _, p := range projects {
		if p.Slug == slug {
			found = true
		}
	}
	if !found {
		// ssh prints this under its own lines, so it names repose.
		return exitf(ExitProjectNotFound, "repose: %s", noSuchProjectMessage(slug))
	}
	_, err = ensureCert(ctx, e.Client, certParams{Handle: me.Handle, Projects: projects}, nil)
	return err
}

// briefErr is err as one short clause for the prepare's warning.
func briefErr(err error) string {
	var nl *notLoggedInError
	if errors.As(err, &nl) {
		return "not logged in; run `repose login`"
	}
	return err.Error()
}

func newSSHPrepareCmd(env func() (*Env, error)) *cobra.Command {
	return &cobra.Command{
		Use:    "ssh-prepare HOST",
		Short:  "Renew the SSH certificate and write the Host block for HOST (run by ssh)",
		Hidden: true,
		Args:   cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			return sshPrepare(cmd.Context(), args[0], env)
		},
	}
}
